from flask_restplus.reqparse import RequestParser
home_parser=RequestParser()
home_parser.add_argument('name',type=str,help='家庭名称',required=True,location='form')
home_parser.add_argument('community_id',type=str,help='社区id',required=True,location='form')
home_parser.add_argument('admin_user_id',type=str,help='户主id',required=True,location='form')
home_parser.add_argument('detail_address',type=str,help='详细地址',required=True,location='form')
home_parser.add_argument('link_name',type=str,help='主人姓名',required=True,location='form')
home_parser.add_argument('telephone',type=str,help='电话',required=True,location='form')
home_parser.add_argument('longitude',type=float,help='家庭经度',required=True,location='form')
home_parser.add_argument('latitude',type=float,help='家庭纬度',required=True,location='form')
home_parser.add_argument('alternate_phone',type=str,help='备用电话',required=True,location='form')
home_parser.add_argument('admin_user_id',type=str,help='管理员id',required=True,location='form')
home_parser.add_argument('gateway_id',type=str,help='网关id',required=True,location='form')

home_parser1=RequestParser()
home_parser1.add_argument('name',type=str,help='家庭名称',required=False,location='form')
home_parser1.add_argument('community_id',type=str,help='社区id',required=False,location='form')
home_parser1.add_argument('admin_user_id',type=str,help='户主id',required=False,location='form')
home_parser1.add_argument('detail_address',type=str,help='详细地址',required=False,location='form')
home_parser1.add_argument('link_name',type=str,help='主人姓名',required=False,location='form')
home_parser1.add_argument('telephone',type=str,help='电话',required=False,location='form')
home_parser1.add_argument('longitude',type=float,help='家庭经度',required=False,location='form')
home_parser1.add_argument('latitude',type=float,help='家庭纬度',required=False,location='form')
home_parser1.add_argument('alternate_phone',type=str,help='备用电话',required=False,location='form')
home_parser1.add_argument('admin_user_id',type=str,help='管理员id',required=False,location='form')
home_parser1.add_argument('gateway_id',type=str,help='网关id',required=False,location='form')


